var tree = [["EventManager","EventManager.html","",
                [["AbstractEventManagerAware","EventManager\/AbstractEventManagerAware.html","",
                [        ]],["AbstractObservable","EventManager\/AbstractObservable.html","",
                [        ]],["Event","EventManager\/Event.html"," < StdEvent",
                [        ]],["EventInterface","EventManager\/EventInterface.html","",
                [        ]],["EventListenerInterface","EventManager\/EventListenerInterface.html","",
                [        ]],["EventManager","EventManager\/EventManager.html","",
                [        ]],["EventManagerAwareInterface","EventManager\/EventManagerAwareInterface.html","",
                [        ]],["EventManagerExtended","EventManager\/EventManagerExtended.html"," < EventManager",
                [        ]],["EventManagerInterface","EventManager\/EventManagerInterface.html","",
                [        ]],["EventObserverProxy","EventManager\/EventObserverProxy.html","",
                [        ]],["EventObserverStorage","EventManager\/EventObserverStorage.html"," < ArrayObject",
                [        ]],["EventSubscriberInterface","EventManager\/EventSubscriberInterface.html","",
                [        ]],["ObservableInterface","EventManager\/ObservableInterface.html","",
                [        ]],["ObserverInterface","EventManager\/ObserverInterface.html","",
                [        ]],["StdEvent","EventManager\/StdEvent.html","",
                [        ]],["StdEventInterface","EventManager\/StdEventInterface.html","",
                [        ]]        ]]        ]

